services:
  db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: filmsdb
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: